#############################################################################
##
##  1_Abelian.g                                      AlgebrasTQD examples
##
##  Anyons of the toric code, double semion, the type-II twisted double of
##  C2 x C2, and the untwisted double D(C4). Usage, from any directory:
##  Read("path/to/AlgebrasTQD/examples/1_Abelian.g");
##
#############################################################################

Read(ReplacedString(INPUT_FILENAME(), "1_Abelian.g", "../AlgebrasTQD.g"));

#Section: prints a heading with a blank line below it
#in: title a string
#out: prints the heading
Section := function(title) Print("\n", title, "\n\n"); end;;

Section("Toric code D(C2)");
ShowAnyons(TQDTheory("C2"));

Section("Double semion");
ShowAnyons(TQDTheory("C2", [1]));

Section("Type-II twisted double of C2 x C2");
K := MakeGroup("C2 x C2");;
a := GroupElement(K, "a");; b := GroupElement(K, "b");;
#xy: finds the binary coordinates of an element of C2 x C2
#in: g an element of the group generated by a and b
#out: [x,y] with g=a^x*b^y
xy := g -> First(Cartesian([0,1],[0,1]), e -> a^e[1]*b^e[2] = g);;
# The additive cocycle exponent x1*y2*y3 gives omega=(-1)^(x1*y2*y3).
omII := rec(a := function(g1,g2,g3)
    return xy(g1)[1]*xy(g2)[2]*xy(g3)[2] mod 2;
end, N := 2);;
if 3coctest([Elements(K), omII]) <> true then
    ErrorNoReturn("The type-II cochain is not a normalized 3-cocycle");
fi;
ShowAnyons(TQDTheory(K, omII));

Section("Untwisted double D(C4)");
ShowAnyons(TQDTheory("C4"));
