#############################################################################
##
##  3_cocycles.g                                     AlgebrasTQD examples
##
##  H^2 and H^3 classes, custom type-II and type-III 3-cocycles, subgroup
##  restrictions, and a comparison of type III with D(D8). Usage, from any
##  directory: Read("path/to/AlgebrasTQD/examples/3_cocycles.g");
##
##  GAP does not fix the order of conjugacy classes, characters or anyons,
##  so spins are compared as collected lists [ value, multiplicity ].
##
#############################################################################

Read(ReplacedString(INPUT_FILENAME(), "3_cocycles.g", "../AlgebrasTQD.g"));

#Section: prints a heading with a blank line below it
#in: title a string
#out: prints the heading
Section := function(title) Print("\n", title, "\n\n"); end;;

#----------------------------------------------------------------------------
# 1. GammaH2Representatives(F) gives one normalized 2-cocycle per class of H^2(F,U(1)). For omega = 1 these are the choices of gamma in A(H,F,gamma,eps).

Section("|H^2(F,U(1))| for a few groups");
for name in [ "C2", "S3", "C2 x C2", "C4 x C2", "D8", "Q8" ] do
    Print(name, ":\t", Length(GammaH2Representatives(MakeGroup(name))), "\n");
od;

#----------------------------------------------------------------------------
# 2. H^3(G,U(1)) = Z_n1 x ... x Z_nr. omf(G) gives one cocycle per class, omaut(G) one per automorphism orbit, and H3Cocycle(G,v) the class with coordinates v. These cocycles are normalized by construction.

Section("H^3(G,U(1)) for a few groups");
Print("GAP prints H^3 as a list of the orders of its cyclic Abelian group factors. For example, [2, 2] means Z2 x Z2.\n");
for name in [ "C2", "S3", "C2 x C2", "D8", "Q8" ] do
    G := MakeGroup(name);;
    Print(name, ":\tH^3 = ", H3Invariants(G), ",\t", Length(omf(G)), " classes, ",
          Length(omaut(G)), " up to automorphisms\n");
od;

Section("The spins of the twisted doubles of S3");
#Spins: collects topological spins with multiplicities
#in: th a theory with its T matrix
#out: the list of [spin,multiplicity] pairs
Spins := th -> Collected(List([1..Length(th.T)], i -> th.T[i][i]));;
S3 := MakeGroup("S3");;
for v in [ 0 .. 5 ] do
    Print("[omega] = ", v, " in Z6:  spins ", Spins(TQDTheory(S3, [ v ], rec(ST := true))), "\n");
od;

#----------------------------------------------------------------------------
# 3. A custom additive 3-cocycle is a record rec(a,N), with omega = exp(2 pi i a/N). The type-II cocycle of C2 x C2 is (-1)^(x1 y2 y3) for g = a^x b^y. Test a custom cocycle once with 3coctest before using it.

Section("Custom type-II cocycle on C2 x C2");
K := MakeGroup("C2 x C2");;
a := GroupElement(K, "a");; b := GroupElement(K, "b");;
#xy: finds the binary coordinates of an element of C2 x C2
#in: g an element of the group generated by a and b
#out: [x,y] with g=a^x*b^y
xy := g -> First(Cartesian([0,1],[0,1]), e -> a^e[1]*b^e[2] = g);;
omII := rec(a := function(g1,g2,g3) return xy(g1)[1]*xy(g2)[2]*xy(g3)[2] mod 2; end, N := 2);;
Print("type II is a normalized 3-cocycle: ", 3coctest([Elements(K), omII]), "\n");

# A subgroup F can condense only if omega restricted to F is trivial in H^3(F,U(1)). gammaf([F,omega]) gives one trivialization per H^2(F,U(1)) class, or fail.
Section("Subgroups of C2 x C2 on which the type-II omega is trivial");
for x in [ a, b, a*b ] do
    gs := gammaf([ Group(x), omII ]);;
    if gs = fail then
        Print("<", GroupLabel(K, x), ">:\tomega is not trivial\n");
    else
        Print("<", GroupLabel(K, x), ">:\t", Length(gs), " trivialization(s) gamma\n");
    fi;
od;

#----------------------------------------------------------------------------
# 4. For C2 x C2 x C2, write g=a^x b^y c^z. The additive type-III cocycle a(g1,g2,g3)=x1*y2*z3 mod 2 gives omega(g1,g2,g3)=(-1)^(x1*y2*z3).

Section("Custom type-III cocycle on C2 x C2 x C2");
K3 := MakeGroup("C2 x C2 x C2");;
a3 := GroupElement(K3, "a");; b3 := GroupElement(K3, "b");; c3 := GroupElement(K3, "c");;
#xyz: finds the binary coordinates of an element of C2 x C2 x C2
#in: g an element of the group generated by a3, b3 and c3
#out: [x,y,z] with g=a3^x*b3^y*c3^z
xyz := g -> First(Cartesian([0,1],[0,1],[0,1]), e -> a3^e[1]*b3^e[2]*c3^e[3] = g);;
omIII := rec(a := function(g1,g2,g3)
    return xyz(g1)[1]*xyz(g2)[2]*xyz(g3)[3] mod 2;
end, N := 2);;
Print("type III is a normalized 3-cocycle: ", 3coctest([Elements(K3), omIII]), "\n");

Section("Subgroups of C2 x C2 x C2 on which the type-III omega is trivial");
for F in List(ConjugacyClassesSubgroups(K3), Representative) do
    if Size(F)>1 then
        gs := gammaf([F, omIII]);;
        Print("generators ", List(GeneratorsOfGroup(F), g -> GroupLabel(K3, g)),
              " (order ", Size(F), "):\t");
        if gs = fail then
            Print("omega is not trivial\n");
        else
            Print(Length(gs), " trivialization(s) gamma\n");
        fi;
    fi;
od;

Section("Type III and D(D8): anyon numbers and spins");
thIII := TQDTheory(K3, omIII, rec(ST := true));;
thD8 := TQDTheory(MakeGroup("D8"), 0, rec(ST := true));;
spIII := Spins(thIII);; spD8 := Spins(thD8);;
sameNumber := Length(thIII.aG) = Length(thD8.aG);;
sameSpins := spIII = spD8;;
Print("type III: ", Length(thIII.aG), " anyons, spins ", spIII, "\n");
Print("D(D8):    ", Length(thD8.aG), " anyons, spins ", spD8, "\n");
Print("same number of anyons: ", sameNumber, "\n");
Print("same spin multiplicities: ", sameSpins, "\n");
if not sameNumber or not sameSpins then
    ErrorNoReturn("The type-III and D(D8) anyon counts or spins differ");
fi;

#----------------------------------------------------------------------------
# 5. 3coctest also rejects a cochain that is not a cocycle. NormalizeCocycle replaces a nonnormalized cocycle by a normalized one in the same class.

Section("Cocycle validation and normalization");
C3 := MakeGroup("C3");;
g := GroupElement(C3, "a");;
bad := rec(a := function(x,y,z) if [x,y,z] = [g,g,g] then return 1; fi; return 0; end, N := 3);;
Print("omega(g,g,g) = E(3) on C3 is a 3-cocycle: ", 3coctest([Elements(C3), bad]), "\n");

C2 := MakeGroup("C2");;
one := One(C2);;
#beta: defines the additive two-cochain used in the normalization example
#in: x and y elements of C2
#out: one at the pair of identities and zero elsewhere
beta := function(x,y) if x = one and y = one then return 1; fi; return 0; end;;
omd := rec(N := 2, a := function(g1,g2,g3)
    return (beta(g2,g3) - beta(g1*g2,g3) + beta(g1,g2*g3) - beta(g1,g2)) mod 2; end);;
Print("d(beta) on C2 is normalized: ", IsNormalizedCocycle(Elements(C2), omd), "\n");
omn := NormalizeCocycle(C2, omd);;
Print("after NormalizeCocycle:      ", 3coctest([Elements(C2), omn]), "\n");
