#############################################################################
##
##  5_interface_map.g                                AlgebrasTQD examples
##
##  Interface maps for the algebras of the toric code, double semion, the type-II twisted double of C2 x C2, and D(S3). The last section compares one braided autoequivalence of D(S3) from each of two routines. Usage, from any directory: Read("path/to/AlgebrasTQD/examples/5_interface_map.g");
##
##  GAP does not fix the order of conjugacy classes, characters, anyons or subgroups, so algebras are found here by their properties, not by position.
##
#############################################################################

# The loader sits one folder above this example file.
Read(ReplacedString(INPUT_FILENAME(), "5_interface_map.g", "../AlgebrasTQD.g"));

#Section: prints a heading with a blank line below it
#in: title a string
#out: prints the heading
Section := function(title) Print("\n", title, "\n\n"); end;;

#----------------------------------------------------------------------------
# 1. Every algebra of the toric code D(C2), including the identity algebra and its two gapped boundaries.

Section("Interface maps for the toric code D(C2)");
C2 := MakeGroup("C2");;
thC2 := TQDTheory(C2);;
for r in AlgebrasWithAnyons(thC2) do
    InterfaceMap(thC2, r);;
od;

#----------------------------------------------------------------------------
# 2. Every algebra of the double semion theory, including its gapped boundary.

Section("Interface maps for the double semion theory");
thDS := TQDTheory(C2, [1]);;
for r in AlgebrasWithAnyons(thDS) do
    InterfaceMap(thDS, r);;
od;

#----------------------------------------------------------------------------
# 3. Every algebra of the type-II twisted C2 x C2 (see examples/1_Abelian.g). The algebra A(<ab>, 1, 1, 1) has the double semion theory as its reduced theory.

Section("Interface maps for the type-II twisted C2 x C2");
K := MakeGroup("C2 x C2");;
a := GroupElement(K, "a");; b := GroupElement(K, "b");;
#xy: finds the binary coordinates of an element of C2 x C2
#in: g an element of the example group generated by a and b
#out: the pair [x,y] with g=a^x*b^y
xy := g -> First(Cartesian([0,1],[0,1]), e -> a^e[1]*b^e[2] = g);;
omII := rec(a := function(g1,g2,g3) return xy(g1)[1]*xy(g2)[2]*xy(g3)[2] mod 2; end, N := 2);;
thK := TQDTheory(K, omII);;
Iab := fail;;
for r in AlgebrasWithAnyons(thK) do
    I := InterfaceMap(thK, r);;
    if r.H = Group(a*b) and IsTrivial(r.F) then Iab := I;; fi;
od;
if Iab = fail then ErrorNoReturn("A(<ab>, 1, 1, 1) was not found"); fi;
# Iab.aK stores the characters of the folded theory G x bar(K). The folding conjugates the characters, so take the complex conjugate to print the spins of the reduced theory.
Print("Spins of the reduced double semion anyons:\n");
for k in [1..Length(Iab.aK)] do
    x := Iab.aK[k];;
    Print(Iab.labK[k], "\t\ttheta=", ComplexConjugate(LookupDictionary(x[2], x[1]) / LookupDictionary(x[2], One(x[1]))), "\n");
od;

#----------------------------------------------------------------------------
# 4. Every non-maximal algebra of D(S3), including the identity algebra. InterfaceMap prints each reduced anyon and its decomposition in the parent theory.

Section("Anyon maps for all non-maximal algebras of D(S3)");
S3 := MakeGroup("S3");;
thS3 := TQDTheory(S3);;
for r in Filtered(AlgebrasWithAnyons(thS3), r -> r.H <> r.F) do
    InterfaceMap(thS3, r);;
od;

#----------------------------------------------------------------------------
# 5. Build the groups generated by the anyon permutation matrices returned by the two automorphism routines and print one nonidentity action from each.

Section("One braided autoequivalence of D(S3) from each routine");
idS3 := [1..Length(thS3.aG)];;
autGeneral := AutomorphismsAnyons(thS3);;
autDavydov := AutomorphismsDG(thS3);;
matGeneral := Group(List(autGeneral,
    r -> PermutationMat(PermList(r.perm), Length(thS3.aG))));;
matDavydov := Group(List(autDavydov,
    r -> PermutationMat(PermList(r.perm), Length(thS3.aG))));;
oneGeneral := First(autGeneral, r -> r.perm <> idS3);;
oneDavydov := First(autDavydov, r -> r.perm <> idS3);;
if oneGeneral = fail or oneDavydov = fail then
    ErrorNoReturn("D(S3): a nonidentity autoequivalence was not found");
fi;
Print("AutomorphismsAnyons matrix group: ", StructureDescription(matGeneral),
      " (order ", Size(matGeneral), ")\n");
Print("AutomorphismsDG matrix group: ", StructureDescription(matDavydov),
      " (order ", Size(matDavydov), ")\n");
Print("AutomorphismsAnyons: ",
      List(Filtered(idS3, i -> oneGeneral.perm[i] <> i),
           i -> [thS3.labels[i], thS3.labels[oneGeneral.perm[i]]]), "\n");
Print("AutomorphismsDG: ",
      List(Filtered(idS3, i -> oneDavydov.perm[i] <> i),
           i -> [thS3.labels[i], thS3.labels[oneDavydov.perm[i]]]), "\n");
